### ISSUE TITLE
didControlTake should be called after secondary receiver pass thread control back

### ISSUE THREAD

**Issue by Calvin-Lin** [bottenderjs/bottender-handovers#6]
https://github.com/bottenderjs/bottender-handovers/blob/master/src/index.js#L53

**Comment by tw0517tw** [comment]
We still need a way to do something after calling the `takeThreadControl()` API regardless of thread is passed or not, so I think it's ok to name this option `didControlTake`.

Maybe we should do what you need by adding another option.
